language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run export
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    # Only deplsoy when the build is on master or main branch - two common default branch names
    # If you're using a different branch name, add it here
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
